name: dls-project
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.3=py310h31b6992_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alsa-lib=1.2.15.3=hb03c661_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-timeout=5.0.1=pyhcf101f3_2
  - attrs=25.4.0=pyhcf101f3_1
  - backports.zstd=1.3.0=py310h69bd2ac_0
  - blas=1.0=mkl
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - brotli-python=1.2.0=py310hba01987_1
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.2=py310h3788b33_0
  - cpython=3.10.19=py310hd8ed1ab_3
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=13.1.115=h4f1e1d6_0
  - cuda-runtime=12.1.0=0
  - cuda-version=13.1=hd92462c_3
  - cycler=0.12.1=pyhcf101f3_2
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dbus=1.16.2=h24cb091_1
  - debugpy=1.8.20=py310h25320af_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - double-conversion=3.3.1=h5888daf_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - ffmpeg=4.4.0=hca11adc_2
  - filelock=3.20.3=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py310h3406613_0
  - freetype=2.14.1=ha770c72_0
  - frozenlist=1.7.0=py310h9548a50_0
  - fsspec=2026.1.0=pyhd8ed1ab_0
  - giflib=5.2.2=hd590300_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py310h63ebcad_2
  - gnutls=3.6.13=h85f3911_1
  - graphite2=1.3.14=hecca717_2
  - gudhi=3.11.0=py310h3f4ba13_7
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.2.0=h15599e2_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.11=pyhd8ed1ab_0
  - intel-openmp=2023.0.0=h9e868ea_25371
  - ipykernel=7.1.0=pyha191276_0
  - ipython=8.37.0=pyh8f84b5b_0
  - ittapi=3.26.6=py310hea6c23e_0
  - ittapi-static=3.26.6=hecca717_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py310haaf941d_2
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.18=h0c24ade_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - lerc=4.0.0=h0aef613_1
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libboost=1.86.0=hed09d94_4
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcblas=3.9.0=13_h8e06fc2_netlib
  - libclang-cpp21.1=21.1.8=default_h99862b1_3
  - libclang13=21.1.8=default_h746c552_3
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.16.1.26=h3b4bcfc_0
  - libcups=2.3.3=hb8b1518_5
  - libcurand=10.4.1.81=h1b6c897_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran-ng=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.3=h8b17d9a_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=he0feb66_16
  - libhwloc=2.12.2=default_hafda6a7_1000
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.9.0=13_h8876d29_netlib
  - libllvm21=21.1.8=hf7376ad_0
  - liblzma=5.8.2=hb03c661_0
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libopengl=1.7.0=ha4b6fd6_2
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.54=h421ea60_0
  - libpq=18.1=h5c52fec_2
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.51.2=h0c1763c_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libtiff=4.7.1=h9d88235_1
  - libuuid=2.41.3=h5347b49_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libvulkan-loader=1.4.341.0=h5279c79_0
  - libwebp=1.6.0=h9635ea4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.13.1=hca5e8e5_0
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libxslt=1.1.43=h711ed8c_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=15.0.7=h0cdce71_0
  - markupsafe=3.0.3=py310h3406613_0
  - matplotlib=3.10.8=py310hff52083_0
  - matplotlib-base=3.10.8=py310hfde16b3_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46344
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multidict=6.7.0=py310h3406613_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nettle=3.6=he412f7d_0
  - networkx=3.4.2=pyh267e887_2
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.4=h55fea9a_0
  - openldap=2.6.10=he970967_0
  - openssl=3.6.1=h35e630c_1
  - pandas=2.3.3=py310h0158d43_2
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.46=h1321c63_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=12.1.0=py310h5a73078_0
  - pip=26.0=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=py310h89163eb_0
  - psutil=7.2.2=py310h139afa4_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - pyside6=6.10.1=py310h2007e60_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.19=h3c07f61_3_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytorch=2.5.1=py3.10_cuda12.1_cudnn9.1.0_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py310h3406613_1
  - pyzmq=27.1.0=py310h4f33d48_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.10.1=hca0d9c9_0
  - readline=8.3=h853b02a_0
  - requests=2.32.5=pyhcf101f3_1
  - scipy=1.15.2=py310h1d65ade_0
  - setuptools=80.10.2=pyh332efcf_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2021.13.0=hb700be7_5
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_h366c992_103
  - torch-geometric=2.6.1=pyhcf101f3_1
  - torchaudio=2.5.1=py310_cu121
  - torchtriton=3.1.0=py310
  - torchvision=0.20.1=py310_cu121
  - tornado=6.5.4=py310ha78b2d2_0
  - tqdm=4.67.3=pyh8f84b5b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - unicodedata2=17.0.0=py310h7c4b9e2_1
  - urllib3=2.6.3=pyhd8ed1ab_0
  - wayland=1.24.0=h3e06ad9_0
  - wcwidth=0.5.3=pyhd8ed1ab_0
  - wheel=0.46.3=pyhd8ed1ab_0
  - x264=1!161.3030=h7f98852_1
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.6=hb03c661_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxcomposite=0.4.7=hb03c661_0
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.7=hb03c661_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.5=hb03c661_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.7=hb03c661_0
  - yaml=0.2.5=h280c20c_3
  - yarl=1.22.0=py310h3406613_0
  - zeromq=4.3.5=h387f397_9
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.3.3=hceb46e0_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - alembic==1.18.3
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.1
      - appdirs==1.4.4
      - backoff==2.2.1
      - blinker==1.9.0
      - boto3==1.42.42
      - botocore==1.42.42
      - cachetools==6.2.6
      - cffi==2.0.0
      - click==8.3.1
      - cloudpickle==3.1.2
      - cryptography==46.0.4
      - dacite==1.6.0
      - dagshub-annotation-converter==0.1.16
      - databricks-sdk==0.85.0
      - dataclasses-json==0.6.7
      - docker==7.1.0
      - egnn-pytorch==0.2.8
      - einops==0.8.2
      - fastapi==0.128.1
      - fastjsonschema==2.21.2
      - flask==3.1.2
      - flask-cors==6.0.2
      - giotto-ph==0.2.4
      - giotto-tda==0.6.2
      - gitdb==4.0.12
      - gitpython==3.1.46
      - google-auth==2.48.0
      - gql==4.0.0
      - graphene==3.4.3
      - graphql-core==3.2.7
      - graphql-relay==3.2.0
      - greenlet==3.3.1
      - gunicorn==23.0.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huey==2.6.0
      - igraph==1.0.0
      - importlib-metadata==8.7.1
      - ipywidgets==8.1.8
      - itsdangerous==2.2.0
      - jmespath==1.1.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyterlab-widgets==3.0.16
      - llvmlite==0.46.0
      - lxml==6.0.2
      - mako==1.3.10
      - markdown-it-py==4.0.0
      - marshmallow==3.26.2
      - mdurl==0.1.2
      - mlflow==3.9.0
      - mlflow-skinny==3.9.0
      - mlflow-tracing==3.9.0
      - mypy-extensions==1.1.0
      - narwhals==2.16.0
      - nbformat==5.10.4
      - numba==0.63.1
      - numpy==1.26.4
      - opentelemetry-api==1.39.1
      - opentelemetry-proto==1.39.1
      - opentelemetry-sdk==1.39.1
      - opentelemetry-semantic-conventions==0.60b1
      - packaging==25.0
      - pathvalidate==3.3.1
      - plotly==6.5.2
      - prettytable==3.17.0
      - protobuf==6.33.5
      - pyarrow==22.0.0
      - pyasn1==0.6.2
      - pyasn1-modules==0.4.2
      - pycparser==3.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyflagser==0.4.7
      - python-dotenv==1.2.1
      - referencing==0.37.0
      - requests-toolbelt==1.0.0
      - rich==14.3.2
      - rpds-py==0.30.0
      - rsa==4.9.1
      - s3transfer==0.16.0
      - scikit-learn==1.3.2
      - semver==3.0.4
      - skops==0.13.0
      - smmap==5.0.2
      - sqlalchemy==2.0.46
      - sqlparse==0.5.5
      - starlette==0.50.0
      - sympy==1.13.1
      - tenacity==9.1.3
      - texttable==1.7.0
      - tomli==2.4.0
      - treelib==1.8.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - uvicorn==0.40.0
      - werkzeug==3.1.5
      - widgetsnbextension==4.0.15
      - zipp==3.23.0
prefix: /home/arutamonofu/miniconda3/envs/dls-project
